(function(){var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(c,a,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");c!=Array.prototype&&c!=Object.prototype&&(c[a]=b.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(c){var a=0;return $jscomp.iteratorPrototype(function(){return a<c.length?{done:!1,value:c[a++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.makeIterator=function(c){$jscomp.initSymbolIterator();var a=c[Symbol.iterator];return a?a.call(c):$jscomp.arrayIterator(c)};$jscomp.arrayFromIterator=function(c){for(var a,b=[];!(a=c.next()).done;)b.push(a.value);return b};$jscomp.arrayFromIterable=function(c){return c instanceof Array?c:$jscomp.arrayFromIterator($jscomp.makeIterator(c))};
$jscomp.polyfill=function(c,a,b,d){if(a){b=$jscomp.global;c=c.split(".");for(d=0;d<c.length-1;d++){var e=c[d];e in b||(b[e]={});b=b[e]}c=c[c.length-1];d=b[c];a=a(d);a!=d&&null!=a&&$jscomp.defineProperty(b,c,{configurable:!0,writable:!0,value:a})}};$jscomp.EXPOSE_ASYNC_EXECUTOR=!0;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(c){function a(){this.batch_=null}if(c&&!$jscomp.FORCE_POLYFILL_PROMISE)return c;a.prototype.asyncExecute=function(b){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(b);return this};a.prototype.asyncExecuteBatch_=function(){var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})};var b=$jscomp.global.setTimeout;a.prototype.asyncExecuteFunction=function(a){b(a,0)};a.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=
this.batch_;this.batch_=[];for(var a=0;a<b.length;++a){var f=b[a];delete b[a];try{f()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};a.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var d=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{b(a.resolve,a.reject)}catch(f){a.reject(f)}};d.prototype.createResolveAndReject_=function(){function b(b){return function(c){f||(f=!0,b.call(a,c))}}var a=this,f=
!1;return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};d.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof d)this.settleSameAsPromise_(b);else{var a;a:switch(typeof b){case "object":a=null!=b;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};d.prototype.resolveToNonPromiseObj_=function(b){var a=void 0;try{a=b.then}catch(f){this.reject_(f);return}"function"==
typeof a?this.settleSameAsThenable_(a,b):this.fulfill_(b)};d.prototype.reject_=function(b){this.settle_(2,b)};d.prototype.fulfill_=function(b){this.settle_(1,b)};d.prototype.settle_=function(b,a){if(0!=this.state_)throw Error("Cannot settle("+b+", "+a|"): Promise already settled in state"+this.state_);this.state_=b;this.result_=a;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=this.onSettledCallbacks_,a=0;a<b.length;++a)b[a].call(),
b[a]=null;this.onSettledCallbacks_=null}};var e=new a;d.prototype.settleSameAsPromise_=function(b){var a=this.createResolveAndReject_();b.callWhenSettled_(a.resolve,a.reject)};d.prototype.settleSameAsThenable_=function(b,a){var f=this.createResolveAndReject_();try{b.call(a,f.resolve,f.reject)}catch(l){f.reject(l)}};d.prototype.then=function(b,a){function f(b,a){return"function"==typeof b?function(a){try{c(b(a))}catch(k){g(k)}}:a}var c,g,e=new d(function(b,a){c=b;g=a});this.callWhenSettled_(f(b,c),
f(a,g));return e};d.prototype["catch"]=function(b){return this.then(void 0,b)};d.prototype.callWhenSettled_=function(b,a){function f(){switch(c.state_){case 1:b(c.result_);break;case 2:a(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?e.asyncExecute(f):this.onSettledCallbacks_.push(function(){e.asyncExecute(f)})};d.resolve=function(b){return b instanceof d?b:new d(function(a,c){a(b)})};d.reject=function(b){return new d(function(a,c){c(b)})};
d.race=function(b){return new d(function(a,c){for(var f=$jscomp.makeIterator(b),g=f.next();!g.done;g=f.next())d.resolve(g.value).callWhenSettled_(a,c)})};d.all=function(b){var a=$jscomp.makeIterator(b),c=a.next();return c.done?d.resolve([]):new d(function(b,f){function l(a){return function(c){g[a]=c;e--;0==e&&b(g)}}var g=[],e=0;do g.push(void 0),e++,d.resolve(c.value).callWhenSettled_(l(g.length-1),f),c=a.next();while(!c.done)})};$jscomp.EXPOSE_ASYNC_EXECUTOR&&(d.$jscomp$new$AsyncExecutor=function(){return new a});
return d},"es6-impl","es3");
var module$src$constants={},SCRIPT_SRC$$module$src$constants="//s.pubmine.com/showad.js",SLOT_ID_PREFIX$$module$src$constants="automattic-id-",SERVER_RESPONSE_HANDLER_NAME$$module$src$constants="automattic_jsonp_handler",PASSBACK_RECEIVER_NAME$$module$src$constants="automattic-passback-receiver",PASSBACK_SRC$$module$src$constants="//s.pubmine.com/passback.html",AD_SERVER_URL$$module$src$constants="//s.pubmine.com/",PASSBACK_ORIGIN$$module$src$constants=window.location.protocol+"//s.pubmine.com";
module$src$constants.SCRIPT_SRC=SCRIPT_SRC$$module$src$constants;module$src$constants.SLOT_ID_PREFIX=SLOT_ID_PREFIX$$module$src$constants;module$src$constants.SERVER_RESPONSE_HANDLER_NAME=SERVER_RESPONSE_HANDLER_NAME$$module$src$constants;module$src$constants.PASSBACK_RECEIVER_NAME=PASSBACK_RECEIVER_NAME$$module$src$constants;module$src$constants.PASSBACK_SRC=PASSBACK_SRC$$module$src$constants;module$src$constants.AD_SERVER_URL=AD_SERVER_URL$$module$src$constants;
module$src$constants.PASSBACK_ORIGIN=PASSBACK_ORIGIN$$module$src$constants;var module$src$lib$showad$utils={};function log$$module$src$lib$showad$utils(c){window.__ATA_DEBUG&&"undefined"!==typeof console&&console.info&&console.info(new Date," -> ",c.replace("http","htt_p"))}
function AdBase$$module$src$lib$showad$utils(){var c=this;this.getFlashVersion=function(){var a=0,b;if(c.isDefined(navigator.plugins)&&"object"===typeof navigator.plugins["Shockwave Flash"])!(b=navigator.plugins["Shockwave Flash"].description)||c.isDefined(navigator.mimeTypes)&&navigator.mimeTypes["application/x-shockwave-flash"]&&!navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin||(b=b.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),a=parseInt(b.replace(/^(.*)\..*$/,"$1"),10));else if(c.isDefined(window.ActiveXObject))try{if(b=
(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"))b=b.split(" ")[1].split(","),a=parseInt(b[0],10)}catch(d){}return a};this.isDefined=function(a){return"undefined"!==typeof a};this.notEmptyVar=function(a){return c.isDefined(a)&&null!==a&&""!==a+""};this.getIEVersion=function(){var a=navigator.userAgent,b=a.indexOf("MSIE ");return-1===b?0:parseFloat(a.substring(b+5,a.indexOf(";",b)))};this.isNetscape=function(){var a=navigator.userAgent;return null!==a.match(/\d\sNavigator\/\d/)||
null!==a.match(/\d\sNetscape\/\d/)};this.isPresto=function(){return-1!==navigator.userAgent.indexOf("Opera")};this.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)};this.getScreenSize=function(){var a=0,b=0;"number"===typeof window.innerHeight?(a=window.innerHeight,b=window.innerWidth):document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)&&(a=document.documentElement.clientHeight,b=document.documentElement.clientWidth);
return{width:b,height:a}};this.getSlotPosition=function(a){a=document.getElementById(a);for(var b=c.getScreenSize(),d=a?a.offsetTop:0;a&&null!==a.offsetParent&&(a=a.offsetParent,d+=a.offsetTop,"BODY"!==a.tagName););(d||0===d)&&b.height?d>b.height?d="btf":d="atf":d="";return d};this.getLang=function(){for(var a=document.getElementsByTagName("meta"),b,c=!1,e=0;e<a.length;e++)if(b=!1,a[e]&&(b=a[e].getAttribute("http-equiv")||a[e].httpEquiv),b&&"content-language"===b.toLowerCase()){c=(c=a[e].getAttribute("content")||
a[e].content)||!1;break}return c}}module$src$lib$showad$utils.log=log$$module$src$lib$showad$utils;module$src$lib$showad$utils.AdBase=AdBase$$module$src$lib$showad$utils;var module$src$lib$showad$ad_renderer={};
function AdRenderer$$module$src$lib$showad$ad_renderer(c){var a=this;this.adManager=c;this.renderSlot=function(b,a){module$src$lib$showad$utils.log('<span class="green">Slot rendering method is invoked for ID:: '+a.slotId+" with "+a.type+" content</span>");b?this.renderSyncSlot(a):this.renderAsyncSlot(a)};this.renderSyncSlot=function(b){"adj"===b.type?document.write('<script type="text/javascript">'+b.data+"\x3c/script>"):document.write(b.data)};this.renderAsyncSlot=function(b){var c,e,h;c=document.getElementById(b.slotId);
if(!c)return module$src$lib$showad$utils.log("Not ready to render: "+b.slotId),!1;e=a.prepareFrame(b);e.src="javascript:\"<html><body style='background:transparent;margin:0%;'></body></html>\"";c.appendChild(e);switch(b.type){case "adj":h='<html><body style=\'background:transparent;margin:0%;\'><script type="text/javascript">var inDapIF=true;\x3c/script><script type="text/javascript">'+b.data+"\x3c/script></body></html>";break;case "adi":h=b.data}b=a.isNetscape();0!==a.getIEVersion()||b?(e=window.frames[e.name],
e.contents=h,e.location.replace(a.getFifLocationIE())):(e=e.contentWindow?e.contentWindow.document:e.contentDocument,-1!==navigator.userAgent.indexOf("Firefox")&&e.open("text/html","replace"),e.write(h),a.isPresto()||e.close());return!0};this.prepareFrame=function(b){var c=document.createElement("iframe"),e="border:none;",h=a.getFrameName(b.slotId);a.notEmptyVar(b.width)&&(e+="width:"+b.width+"px;",c.width=b.width);a.notEmptyVar(b.height)&&(e+="height:"+b.height+"px;",c.height=b.height);c.setAttribute("style",
e);c.setAttribute("frameBorder","0");c.setAttribute("scrolling","no");c.name=h;c.id=h;return c};this.getFifLocationIE=function(){return a.isNetscape()&&!a.adManager.isSyncMode()?"javascript:document.write(window.contents);":"javascript:window.contents"};this.getFrameName=function(b){return"fif_slot_"+module$src$constants.SLOT_ID_PREFIX+"_"+b};this.addEvent=function(b,a,c,h){b.addEventListener?b.addEventListener(a,c,h):b.attachEvent("on"+a,function(){return c.call(b,window.event)})}}
AdRenderer$$module$src$lib$showad$ad_renderer.prototype=new module$src$lib$showad$utils.AdBase;AdRenderer$$module$src$lib$showad$ad_renderer.prototype.constructor=AdRenderer$$module$src$lib$showad$ad_renderer;module$src$lib$showad$ad_renderer.AdRenderer=AdRenderer$$module$src$lib$showad$ad_renderer;var module$src$lib$showad$ad_manager={};AdManager$$module$src$lib$showad$ad_manager.prototype=new module$src$lib$showad$utils.AdBase;AdManager$$module$src$lib$showad$ad_manager.prototype.constructor=AdManager$$module$src$lib$showad$ad_manager;
function AdManager$$module$src$lib$showad$ad_manager(c){function a(b,a){for(var c=b.length,f=[],d={};c--;){if("A9"===b[c].provider&&"timeout"!==b[c].response)if(e[a])continue;else e[a]=!0;if("PM"===b[c].provider&&"timeout"!==b[c].response)if(h[a])continue;else h[a]=!0;d[b[c].provider]||(d[b[c].provider]=!0,f.unshift(b[c]))}return f}var b=this,d="section_id tz fl click3rd slot_id ref pos".split(" ");this.slotsDefs={};this.customUserGroup=this.tuuidCookieChecked=this.passbackInited=!1;this.globalPart=
c;this.adRenderer=new module$src$lib$showad$ad_renderer.AdRenderer(this);this.getSlotDefById=function(b){return this.slotsDefs[b]};this.initPassbackWorkflow=function(){if(!b.passbackInited){b.passbackInited=!0;var a=document.createElement("iframe");a.style.cssText="position:absolute;left:-1000px;top:-1000px;border:0 solid;width:0;height:0;";a.width=a.height=0;a.name=module$src$constants.PASSBACK_RECEIVER_NAME;a.src=module$src$constants.PASSBACK_SRC+"#"+location.protocol+"//"+location.host;document.body.appendChild(a);
b.onPassbackReceived=b.globalPart.onPassbackReceived=function(a){var c,f=a.id,f=f&&f.replace("fif_slot_"+module$src$constants.SLOT_ID_PREFIX+"_","");if((c=b.getSlotDefById(f))&&c.subs&&c.subs.length){try{a.id=a.name="dead_"+a.name;a.style.cssText="border:none;position:absolute;width:0;height:0;left:-10000px;top:-10000px;";var d=a.contentWindow;d.name=a.id;d&&d.document&&"complete"===d.document.readyState&&a.parentNode&&a.parentNode.removeChild(a)}catch(q){}a=c.subs.shift();c.passbackUrl&&((new Image).src=
c.passbackUrl);a.noad_url&&((new Image).src=a.noad_url);c={slotId:f,sectionId:c.sectionId,data:a.data,type:c.type,width:c.width,height:c.height,subs:c.subs,passbackUrl:a.passback_url};b.slotsDefs[c.slotId]=c;b.adRenderer.renderSlot(b.isSyncMode(),c)}};b.adRenderer.addEvent(window,"message",function(a){if(a.origin===module$src$constants.PASSBACK_ORIGIN&&a.source){a=a.source;for(var c=a.parent;c!==window&&c!==window.top;)a=c,c=c.parent;if(a&&c===window)try{b.onPassbackReceived(a.frameElement)}catch(n){module$src$lib$showad$utils.log("No access to iframe from postMessage "+
n)}}})}};this.displayAd=function(a,c){module$src$lib$showad$utils.log('<span class="blue">displayAd is called for ID:</span> '+a);var d=b.globalPart.ids;d&&d[a]&&delete d[a];var f,e,g,h,p,k,m;e=document.getElementById(a);h=parseInt(e.style.width,10);p=parseInt(e.style.height,10);g=e.getAttribute("data-type")||"adj";m=b.globalPart.customParams;d=module$src$constants.AD_SERVER_URL;if(c)for(f in k={},c)c.hasOwnProperty(f)&&(k[f]=c[f]);if(m)for(f in k||(k={}),m)m.hasOwnProperty(f)&&!k.hasOwnProperty(f)&&
(k[f]=m[f]);f={slotId:a,sectionId:e.getAttribute("data-section"),forcedUrl:e.getAttribute("data-forcedurl"),customParams:k,type:g,width:h,height:p};d=f.forcedUrl||b.generateAdServerUrl(d,f);module$src$lib$showad$utils.log("Ad server full URL: "+d);b.requestAd(f,d)};this.addJsonpHandler=function(a,b){var c,f=this.serverResponseHandler,d=this;c=(module$src$constants.SERVER_RESPONSE_HANDLER_NAME+"_"+a.slotId).replace(/[^a-zA-Z0-9_\$]/g,"_");window[c]=function(b){try{delete window[c]}catch(k){window[c]=
void 0}var e=document.getElementById("slots_script_"+a.slotId);e&&e.parentNode.removeChild(e);f.call(d,b,a)};var e=b.indexOf("?");return b+((-1<e?"&":"?")+"callbackPubmine="+c)};this.requestAd=function(a,c){var d,f,e;c=b.addJsonpHandler(a,c);d="slots_script_"+a.slotId;b.isSyncMode()?(d='<script type="text/javascript" src="{{url}}" id="{{id}}">\x3c/script>'.replace("{{url}}",c).replace("{{id}}",d),document.write(d)):(f=document.createElement("script"),f.async=!0,f.type="text/javascript",f.src=c,f.id=
d,e=document.getElementsByTagName("script")[0],b.isPresto()?setTimeout(function(){e.parentNode.insertBefore(f,e)},0):e.parentNode.insertBefore(f,e))};this.serverResponseHandler=function(a,c){var d=c.customParams;a&&a.data?(c.data=a.data,c.passbackUrl=a.passback_url,c.subs=a.subs,b.slotsDefs[c.slotId]=c,c.subs&&c.subs.length&&b.initPassbackWorkflow(),d&&"function"===typeof d.renderStartCallback&&d.renderStartCallback(c),b.adRenderer.renderSlot(b.isSyncMode(),c)):d&&"function"===typeof d.noContentCallback&&
d.noContentCallback(c,a)};this.checkNotRendered=function(){var a,b,c;b=this.globalPart.ids;if(null!==b&&"object"===typeof b){try{c=this.globalPart.customParams||{}}catch(n){return}for(a in b)b.hasOwnProperty(a)&&this.displayAd(a,c)}};var e={},h={};this.generateAdServerUrl=function(c,d){d=d||{};var e,f,g,h;e="https:"===document.location.protocol;g=[];h=this.getLang();f=c.replace(/^http:|^https:|\?$/im,"");f=(e?"https:":"http:")+f+d.type+"/";e="";top!==self&&(e=encodeURIComponent(document.referrer));
e=["tz="+(new Date).getTimezoneOffset(),"fl="+b.getFlashVersion(),"ref="+e||"","pos="+b.getSlotPosition(d.slotId)||"","sfv=2"];f+=d.sectionId+"/"+d.width+"/"+d.height+"/";g=g.concat(e);"undefined"!=typeof b.globalPart.providerData&&b.globalPart.providerData.length&&b.addCustomParams({headerbidding:JSON.stringify(a(b.globalPart.providerData,d.width+"x"+d.height))},g);b.checkCookie();b.customUserGroup&&b.addCustomParams({user_group:b.customUserGroup},g);b.addCustomParams(d.customParams,g);"undefined"!==
typeof b.globalPart.click3rd&&g.push("click3rd="+encodeURIComponent(b.globalPart.click3rd));!1!==h&&g.push("lang="+encodeURIComponent(h));return f+"?"+g.join("&")+"&ord="+Math.floor(1E13*Math.random())};this.checkCookie=function(){if(!b.tuuidCookieChecked){var a=("; "+document.cookie).match(";\\s*tuuid=([^;]+)");a&&a[1]||(b.tuuidCookieChecked=!0,b.customUserGroup=Math.min(15,Math.floor(16*Math.random())).toString(16))}};this.addCustomParams=function(a,c){var e,f;if("undefined"!==typeof a)a:for(e in a){f=
0;for(var g=d.length;f<g;f++)if(d[f]+""===e+"")continue a;if(a.hasOwnProperty(e)){f=a[e];if(b.isArray(f)){for(g=0;g<f.length;g++)f[g]=encodeURIComponent(f[g]);c.push(e+"="+f.join("|"));continue a}c.push(e+"="+encodeURIComponent(f))}}};this.isSyncMode=function(){return!0===b.globalPart.isSync};this.checkNotRendered()}module$src$lib$showad$ad_manager.AdManager=AdManager$$module$src$lib$showad$ad_manager;var module$src$lib$header_bidding$utils={};function createErrorLogUrl$$module$src$lib$header_bidding$utils(c){var a=encodeURI(c.name);c=encodeURI(c.message);return"/jslog?v=1&s=err&n="+a+"&m="+c}function logError$$module$src$lib$header_bidding$utils(c,a){a=void 0===a?new Image:a;a.src=module$src$constants.AD_SERVER_URL+createErrorLogUrl$$module$src$lib$header_bidding$utils(c)}
function loadScript$$module$src$lib$header_bidding$utils(c){return new Promise(function(a,b){var d=document.createElement("script");d.type="text/javascript";d.async=!0;d.readyState?d.onreadystatechange=function(){if("loaded"===d.readyState||"complete"===d.readyState)d.onreadystatechange=null,a()}:(d.onload=function(){a()},d.onerror=function(){b(!0)});d.src=c;var e=document.getElementsByTagName("head"),e=e.length?e:document.getElementsByTagName("body");e.length&&(e=e[0],e.insertBefore(d,e.firstChild))})}
module$src$lib$header_bidding$utils.createErrorLogUrl=createErrorLogUrl$$module$src$lib$header_bidding$utils;module$src$lib$header_bidding$utils.logError=logError$$module$src$lib$header_bidding$utils;module$src$lib$header_bidding$utils.loadScript=loadScript$$module$src$lib$header_bidding$utils;var module$src$lib$header_bidding$adapters$amazon={},key$$module$src$lib$header_bidding$adapters$amazon="A9",timeout$$module$src$lib$header_bidding$adapters$amazon=3E3;
function getBids$$module$src$lib$header_bidding$adapters$amazon(c){var a=setTimeout(function(){c({key:key$$module$src$lib$header_bidding$adapters$amazon,success:!1,response:"timeout"})},timeout$$module$src$lib$header_bidding$adapters$amazon),b=window.amznads;window.amznads?b.getAdsCallback("3033",function(){clearTimeout(a);c({key:key$$module$src$lib$header_bidding$adapters$amazon,success:!0,response:b.getKeys()})},timeout$$module$src$lib$header_bidding$adapters$amazon):c({key:key$$module$src$lib$header_bidding$adapters$amazon,
success:!1,response:"loaderror"})}var amazonAdapter$$module$src$lib$header_bidding$adapters$amazon={getBids:getBids$$module$src$lib$header_bidding$adapters$amazon};module$src$lib$header_bidding$adapters$amazon.amazonAdapter=amazonAdapter$$module$src$lib$header_bidding$adapters$amazon;var module$src$lib$header_bidding$adapters$pubmatic={},key$$module$src$lib$header_bidding$adapters$pubmatic="PM",timeout$$module$src$lib$header_bidding$adapters$pubmatic=3E3,providerUrl$$module$src$lib$header_bidding$adapters$pubmatic="//ads.pubmatic.com/AdServer/js/gshowad.js",slots$$module$src$lib$header_bidding$adapters$pubmatic=["1187555071@300x250","1187555072@728x90","1187555073@300x250","1187555074@160x600"];
function getObjectValues$$module$src$lib$header_bidding$adapters$pubmatic(c){c=void 0===c?{}:c;var a=[],b;for(b in c)c.hasOwnProperty(b)&&a.push(c[b]);return a}
function getBids$$module$src$lib$header_bidding$adapters$pubmatic(c){var a=setTimeout(function(){c({key:key$$module$src$lib$header_bidding$adapters$pubmatic,success:!1,response:"timeout"})},timeout$$module$src$lib$header_bidding$adapters$pubmatic);window.pm_optimize_adslots=slots$$module$src$lib$header_bidding$adapters$pubmatic;window.pm_pub_id=156204;window.pm_async_callback_fn="pm_automattic_pubmatic_adaptor";window.pm_automattic_pubmatic_adaptor=function(){var b=window.progKeyValueMap;clearTimeout(a);
c({key:key$$module$src$lib$header_bidding$adapters$pubmatic,success:!0,response:getObjectValues$$module$src$lib$header_bidding$adapters$pubmatic(b)})};module$src$lib$header_bidding$utils.loadScript(providerUrl$$module$src$lib$header_bidding$adapters$pubmatic).then(function(){},function(a){a&&module$src$lib$header_bidding$utils.logError(a);c({key:key$$module$src$lib$header_bidding$adapters$pubmatic,success:!1,response:"loaderror"})})}
var pubmaticAdapter$$module$src$lib$header_bidding$adapters$pubmatic={getBids:getBids$$module$src$lib$header_bidding$adapters$pubmatic};module$src$lib$header_bidding$adapters$pubmatic.pubmaticAdapter=pubmaticAdapter$$module$src$lib$header_bidding$adapters$pubmatic;var module$src$lib$header_bidding$adapters$index={},adapters$$module$src$lib$header_bidding$adapters$index=[module$src$lib$header_bidding$adapters$amazon.amazonAdapter,module$src$lib$header_bidding$adapters$pubmatic.pubmaticAdapter];module$src$lib$header_bidding$adapters$index.adapters=adapters$$module$src$lib$header_bidding$adapters$index;var automattic$$module$src$index={version:1,customParams:window._ipw_custom,providerData:[],tasks:[],initAd:function(c){var a=c=void 0===c?{}:c,b=void 0===a.sectionId?0:a.sectionId,d=void 0===a.width?0:a.width,e=void 0===a.height?0:a.height,h=a.type,a=a.forcedUrl,g=this.id();document.write('<div id="'+g+'" data-section="'+b+'"'+((a?'data-forcedurl="'+a+'"':"")+" "+(h?'data-type="'+h+'"':""))+('style="width: '+d+"px; height: "+e+'px;"></div>'));this.displayAd(g,c.customParams)},registerAdapterResult:function(c,
a,b){a&&this.providerData.push({provider:c,response:a,responsetime:b||""})},id:function(){return module$src$constants.SLOT_ID_PREFIX+(parseInt(1E4*Math.random(),10)+1+(new Date).getMilliseconds())},getBids:function(){for(var c=this,a=[],b=Date.now(),d=function(a){c.registerAdapterResult(a.key,a.response,Date.now()-b)},e=$jscomp.makeIterator(module$src$lib$header_bidding$adapters$index.adapters),h=e.next();!h.done;h=e.next())h=new Promise(h.value.getBids),h.then(d,module$src$lib$header_bidding$utils.logError),
a.push(h);return Promise.all(a)},displayAd:function(c){for(var a=[],b=0;b<arguments.length;++b)a[b-0]=arguments[b];this.tasks.push(a)},runDisplayTasks:function(){for(var c=$jscomp.makeIterator(this.tasks),a=c.next();!a.done;a=c.next())this.adManager.displayAd.apply(this.adManager,[].concat($jscomp.arrayFromIterable(a.value)))},init:function(){var c=this;this.adManager=new module$src$lib$showad$ad_manager.AdManager(this);this.getBids(module$src$lib$header_bidding$adapters$index.adapters).then(function(){return c.runDisplayTasks()},
module$src$lib$header_bidding$utils.logError)}};automattic$$module$src$index.init();window.__ATA=automattic$$module$src$index;}).call(this);
