import psutil
import os

print("==========================================================")
print("           COMPLETE PSUTIL MODULE METHOD PROFILE          ")
print("==========================================================\n")

# 1. psutil.cpu_percent()
print(" psutil.cpu_percent(interval=0.1)")
res_cpu = psutil.cpu_percent(interval=0.1)
print("Executed command : Measure total CPU utilization percentage over an interval")
print(f"Returned Type    : {type(res_cpu)}")
print(f"Printed Object   : {res_cpu}")
print(f"Captured stdout  : {res_cpu}\n")

# 2. psutil.virtual_memory()
print(" psutil.virtual_memory()")
res_mem = psutil.virtual_memory()
print("Executed command : Fetch complete RAM usage metrics statistics")
print(f"Returned Type    : {type(res_mem)}")
print(f"Printed Object   : {res_mem}")
print("Captured stdout  : System memory usage fields like total, available, used\n")

# 3. psutil.swap_memory()
print(" psutil.swap_memory()")
res_swap = psutil.swap_memory()
print("Executed command : Retrieve disk swap space utilization metadata")
print(f"Returned Type    : {type(res_swap)}")
print(f"Printed Object   : {res_swap}")
print(f"Captured stdout  : {res_swap}\n")

# 4. psutil.disk_partitions()
print(" psutil.disk_partitions()")
res_parts = psutil.disk_partitions()
print("Executed command : Enumerate all mounted disk hardware partitions")
print(f"Returned Type    : {type(res_parts)}")
print(f"Printed Object   : {res_parts[:1]} ... (Truncated)")
print("Captured stdout  : Array of storage node attachment profiles\n")

# 5. psutil.disk_usage()
print(' psutil.disk_usage("/")')
res_dusage = psutil.disk_usage("/")
print("Executed command : Query filesystem usage on targeted mount path node")
print(f"Returned Type    : {type(res_dusage)}")
print(f"Printed Object   : {res_dusage}")
print(f"Captured stdout  : {res_dusage}\n")

# 6. psutil.net_io_counters()
print(" psutil.net_io_counters()")
res_netio = psutil.net_io_counters()
print("Executed command : Gather global network packet I/O tracking counters")
print(f"Returned Type    : {type(res_netio)}")
print(f"Printed Object   : {res_netio}")
print("Captured stdout  : System-wide byte sent and received counts\n")

# 7. psutil.users()
print(" psutil.users()")
res_users = psutil.users()
print("Executed command : List currently connected interactive users on host")
print(f"Returned Type    : {type(res_users)}")
print(f"Printed Object   : {res_users}")
print("Captured stdout  : Login terminal terminal session profiles\n")

# 8. psutil.boot_time()
print(" psutil.boot_time()")
res_boot = psutil.boot_time()
print("Executed command : Extract hardware system epoch boot timestamp")
print(f"Returned Type    : {type(res_boot)}")
print(f"Printed Object   : {res_boot}")
print(f"Captured stdout  : {res_boot}\n")

# 9. psutil.pids()
print(" psutil.pids()")
res_pids = psutil.pids()
print("Executed command : Query complete array of all running Process IDs")
print(f"Returned Type    : {type(res_pids)}")
print(f"Printed Object   : {res_pids[:5]} ... (Truncated)")
print("Captured stdout  : Array tracking active core PIDs\n")

# 10. psutil.Process()
print(f" psutil.Process({os.getpid()})")
res_proc = psutil.Process(os.getpid())
print(
    "Executed command : Instantiate process wrapper tracker handle for current script"
)
print(f"Returned Type    : {type(res_proc)}")
print(f"Printed Object   : {res_proc}")
print("Captured stdout  : Object reference linking active PID state details\n")

# 11. Process Instance Method: name()
print(f" psutil.Process({os.getpid()}).name()")
res_pname = res_proc.name()
print("Executed command : Resolve application executable name from process hook")
print(f"Returned Type    : {type(res_pname)}")
print(f"Printed Object   : '{res_pname}'")
print(f"Captured stdout  : '{res_pname}'\n")

# 12. Process Instance Method: memory_info()
print(f" psutil.Process({os.getpid()}).memory_info()")
res_pminfo = res_proc.memory_info()
print(
    "Executed command : Measure specific memory footprint allocations for target process"
)
print(f"Returned Type    : {type(res_pminfo)}")
print(f"Printed Object   : {res_pminfo}")
print("Captured stdout  : Application specific RSS and VMS byte metrics\n")
