---
- hosts: localhost
  gather_facts: yes
  become: yes

  tasks:
  - name: Installing required packages
    apt: 
      name: ['vim', 'tmux', 'iftop', 'zsh', 'net-tools']
      update_cache: yes
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'
