---
- hosts: localhost
  gather_facts: yes
  become: yes

  tasks:
  - name: Install kvm related packages
    apt:
      name: ['cpu-checker', 'qemu', 'qemu-kvm', 'libvirt-bin', 'bridge-utils', 'virt-manager']
      update_cache: yes
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'

  - name: Make libvirtd service start and enable at boot time
    service:
      name: libvirtd
      state: started
      enabled: yes
