
apiVersion: v1
kind: ReplicationController
metadata:
  name: apache2
spec:
  replicas: 2
  selector:
    app: apache2
  template:
    metadata:
      name: apache2
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2
        image: teamrock/apache2
        ports:
        - containerPort: 80
