
$ salt kube-master cmd.run "kubectl get pods masum-web-5cvf1 -o yaml"
kube-master:
    apiVersion: v1
    kind: Pod
    metadata:
      annotations:
        kubernetes.io/created-by: |
          {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"default","name":"masum-web","uid":"3a577842-127f-11e9-928a-525400dfde7f","apiVersion":"v1","resourceVersion":"121853"}}
      creationTimestamp: 2019-01-07T13:44:42Z
      generateName: masum-web-
      labels:
        run: masum-web
      name: masum-web-5cvf1
      namespace: default
      ownerReferences:
      - apiVersion: v1
        controller: true
        kind: ReplicationController
        name: masum-web
        uid: 3a577842-127f-11e9-928a-525400dfde7f
      resourceVersion: "128763"
      selfLink: /api/v1/namespaces/default/pods/masum-web-5cvf1
      uid: 629e62be-1282-11e9-928a-525400dfde7f
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: masum-web
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      nodeName: kube-master
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
    status:
      conditions:
      - lastProbeTime: null
        lastTransitionTime: 2019-01-07T13:44:42Z
        status: "True"
        type: Initialized
      - lastProbeTime: null
        lastTransitionTime: 2019-01-07T19:17:59Z
        status: "True"
        type: Ready
      - lastProbeTime: null
        lastTransitionTime: 2019-01-07T13:44:42Z
        status: "True"
        type: PodScheduled
      containerStatuses:
      - containerID: docker://7692476e6700b02083cb7f8c0bcda37918397004c48d7341fe4ebe38da893721
        image: nginx
        imageID: docker-pullable://docker.io/nginx@sha256:b543f6d0983fbc25b9874e22f4fe257a567111da96fd1d8f1b44315f1236398c
        lastState:
          terminated:
            containerID: docker://3e3bd78dc65e4c040821368b9915ab34655e01aed5169a48205735419e8e0054
            exitCode: 0
            finishedAt: 2019-01-07T15:22:06Z
            reason: Completed
            startedAt: 2019-01-07T14:28:12Z
        name: masum-web
        ready: true
        restartCount: 2
        state:
          running:
            startedAt: 2019-01-07T19:17:58Z
      hostIP: 192.168.122.146
      phase: Running
      podIP: 172.17.0.2
      startTime: 2019-01-07T13:44:42Z
root:~/ $

root@kube-master ~]# cat mahrus.yaml

apiVersion: v1
kind: Pod

... kind is pod. pod will be created

metadata:
  name: mahrus

... name of the pod will be mahrus

spec:
  containers:
  - image: httpd:latest

... from which container this pod will
... created.

    name: mahrus-http

... and the new container name will be
... mahrus-http

    ports:
    - containerPort: 8080
      protocol: TCP

... container port will be 8080 and protocol
... will be TCP.

... and finally the yaml defination is

apiVersion: v1
kind: pod
metadata:
  name: mahrus
spec:
  containers:
  - image: httpd:latest
    name: mahrus-http
    ports:
    - containerPort: 8080
      protocol: TCP

[root@kube-master ~]#

... now create the pod from yaml defination file.

root:~/ $ salt kube-master cmd.run "kubectl create -f mahrus.yaml"
kube-master:
    pod "mahrus" created
root:~/ $


