mul_table:
	gcc -o mul_table.o mul_table.c

mul_run:
	./mul_table.o

argument_compile:
	gcc -o argument.o argument.c

argument_run:
	./argument.o what is this

uname_cpl:
	gcc -o uname_masum uname.c

uname_run:
	./uname_masum

clean:
	rm -fr *.o
